const DATA = [
    {name: "Авангард", type: "Современный", relatedStyles: ["Конструктивизм"], path: "avant-garde", styleOrder: "after"},
    {name: "Ампир", type: "Классический", relatedStyles: ["Античный", "Барокко", "Классический", "Рококо", "Ренессанс"], path: "empire",
    styleOrder: "after"},
    {name: "Античный", type: "Классический", relatedStyles: ["Ампир", "Барокко", "Классический", "Рококо", "Ренессанс"], path: "antique",
    styleOrder: "before"},
    {name: "Ар-деко", type: "Современный", relatedStyles: ["Модерн"], path: "art-deco", styleOrder: "after"},
    {name: "Африканский", type: "Этнический", relatedStyles: ["Египетский", "Этнический"], path: "african", styleOrder: "before"},
    {name: "Барокко", type: "Классический", relatedStyles: ["Классический", "Ампир", "Рококо", "Ренессанс"], path: "baroque", styleOrder: "after"},
    {name: "Брутальный", type: "Современный", relatedStyles: ["Лофт"], path: "brutal", styleOrder: "before"},
    {name: "Восточный", type: "Этнический", relatedStyles: ["Этнический"], path: "oriental", styleOrder: "before"},
    {name: "Готический", type: "Классический", relatedStyles: ["Романский"], path: "gothic", styleOrder: "before"},
    {name: "Египетский", type: "Этнический", relatedStyles: ["Африканский", "Этнический"], path: "egyptian", styleOrder: "before"},
    {name: "Кантри", type: "Классический", relatedStyles: ["Прованс", "Шале"], path: "country", styleOrder: "after"},
    {name: "Китайский", type: "Этнический", relatedStyles: ["Японский", "Этнический"], path: "chinese", styleOrder: "before"},
    {name: "Китч", type: "Современный", relatedStyles: ["Эклектика"], path: "kitsch", styleOrder: "kitsch"},
    {name: "Классический", type: "Классический", relatedStyles: ["Неоклассицизм", "Консерватизм", "Ампир", "Рококо", "Ренессанс"], path: "classic", styleOrder: "before"},
    {name: "Консерватизм", type: "Классический", relatedStyles: ["Неоклассицизм"], path: "conservative", styleOrder: "after"},
    {name: "Конструктивизм", type: "Современный", relatedStyles: ["Авангард"], path: "constructivism", styleOrder: "after"},
    {name: "Лофт", type: "Современный", relatedStyles: ["Брутальный"], path: "loft", styleOrder: "after"},
    {name: "Минимализм", type: "Современный", relatedStyles: ["Скандинавский"], path: "minimalism", styleOrder: "after"},
    {name: "Модерн", type: "Современный", relatedStyles: ["Ар-деко"], path: "modern", styleOrder: "after"},
    {name: "Неоклассицизм", type: "Современный", comment:"Этот стиль можно назвать переходным, сочетающим в себе черты классического и современного стилей",
    relatedStyles: ["Классический"], path: "neoclassic", styleOrder: "after"},
    {name: "Поп-арт", type: "Современный", path: "pop-art", styleOrder: "after"},
    {name: "Постмодернизм", type: "Современный", path: "postmodern", styleOrder: "after"},
    {name: "Прованс", type: "Классический", relatedStyles: ["Кантри", "Шале"], path: "provence", styleOrder: "after"},
    {name: "Ренессанс", type: "Классический", relatedStyles: ["Ампир", "Античный", "Барокко", "Классический", "Рококо"], path: "renaissance", styleOrder: "after"},
    {name: "Рококо", type: "Классический", relatedStyles: ["Ампир", "Античный", "Барокко", "Классический", "Ренессанс"], path: "rococo", styleOrder: "after"},
    {name: "Романский", type: "Классический", relatedStyles: ["Готический"], path: "romanesque", styleOrder: "before"},
    {name: "Скандинавский", type: "Современный", relatedStyles: ["Минимализм"], path: "scandinavian", styleOrder: "before"},
    {name: "Техно", type: "Современный", relatedStyles: ["Хай-тек"], path: "techno", styleOrder: "after"},
    {name: "Хай-тек", type: "Современный", relatedStyles: ["Техно"], path: "high-tech", styleOrder: "after"},
    {name: "Шале", type: "Классический", relatedStyles: ["Кантри", "Прованс"], path: "chalet", styleOrder: "after"},
    {name: "Эклектика", type: "Современный", comment:"Строго говоря, этот стиль может включать в себя стили из любых категорий", relatedStyles: ["Китч"], path: "eclecticism", styleOrder: "after"},
    {name: "Этнический", type: "Этнический", relatedStyles: ["Африканский", "Восточный", "Египетский", "Китайский", "Японский"], path: "ethnic", styleOrder: "before"},
    {name: "Японский", type: "Этнический", relatedStyles: ["Китайский", "Этнический"], path: "japanese", styleOrder: "before"},
];

export default DATA;